# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-06 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_auto_20171007_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='distance',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='api',
            name='moisture',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
